Initilization_simulink

ballSelectionMode=2;
lineDetectionEnabled=1;
while 1
    
    inputFrame = getFramePi();
    
    [ballPosition,... 
     selectedLines,... 
     outputFrame] = detectionSkill(ballSelectionMode,... 
                                   lineDetectionEnabled,...
                                   referenceImage,...
                                   inputFrame);
end
